packages:
  - .
  - packages/*
overrides:
  body-parser: 2.3.0
  dompurify: 3.4.15
  path-to-regexp: 8.4.0
  qs: 6.16.0
allowBuilds:
  '@parcel/watcher': true
  '@vscode/vsce-sign': true
  esbuild: true
  keytar: true
  lefthook: true

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@vscode/vsce-sign'
  - esbuild
  - keytar
  - lefthook
